//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petuda.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petuda.Views.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петуда – это новое слово в КВН-е. Это попытка облегчить и ускорить техническую часть работы команды со своим материалом..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вести базу шуток команды (добавлять, редактировать и удалять шутки).
        /// </summary>
        public static string AboutBase {
            get {
                return ResourceManager.GetString("AboutBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко собирать из шуток сценарии, просто перетягивая их из базы в сценарий.
        /// </summary>
        public static string AboutScripts {
            get {
                return ResourceManager.GetString("AboutScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстро и удобно находить шутки в базе.
        /// </summary>
        public static string AboutSearch {
            get {
                return ResourceManager.GetString("AboutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически создавать Word-файл собранного сценария.
        /// </summary>
        public static string AboutWord {
            get {
                return ResourceManager.GetString("AboutWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы добавить выбранную шутку в открытый сценарий.
        /// </summary>
        public static string AddJokeToScriptToolTip {
            get {
                return ResourceManager.GetString("AddJokeToScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В сценарий.
        /// </summary>
        public static string AddToScript {
            get {
                return ResourceManager.GetString("AddToScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы изменить «шапку» открытого сценария.
        /// </summary>
        public static string ChangeScriptToolTip {
            get {
                return ResourceManager.GetString("ChangeScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы добавить новую шутку в базу.
        /// </summary>
        public static string CreateJokeToolTip {
            get {
                return ResourceManager.GetString("CreateJokeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая версия: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы отфильтровать шутки по дате создания – выбирите нужный временной промежуток.
        /// </summary>
        public static string DateFilterToolTip {
            get {
                return ResourceManager.GetString("DateFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата : .
        /// </summary>
        public static string DateTitle {
            get {
                return ResourceManager.GetString("DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы удалить выбранную шутку из базы. Шутка, так же, будет удалена из всех сценариев, в которых она используется.
        /// </summary>
        public static string DeleteJokeToolTip {
            get {
                return ResourceManager.GetString("DeleteJokeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы удалить открытый сценарий.
        /// </summary>
        public static string DeleteScriptToolTip {
            get {
                return ResourceManager.GetString("DeleteScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы изменить содержимое выбранной шутки, либо просто дважды кликните по шутке в списке.
        /// </summary>
        public static string EditJokeToolTip {
            get {
                return ResourceManager.GetString("EditJokeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата игры:.
        /// </summary>
        public static string GameDate {
            get {
                return ResourceManager.GetString("GameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата игры :.
        /// </summary>
        public static string GameDateTitle {
            get {
                return ResourceManager.GetString("GameDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя изменять, или удалять сценарии прошедших игр – это уже история..
        /// </summary>
        public static string GameDateToolTip {
            get {
                return ResourceManager.GetString("GameDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать Word-файл сценария.
        /// </summary>
        public static string GenerateWordFile {
            get {
                return ResourceManager.GetString("GenerateWordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vk.com/petuda.
        /// </summary>
        public static string GroupLink {
            get {
                return ResourceManager.GetString("GroupLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить обновление.
        /// </summary>
        public static string InstallUpdate {
            get {
                return ResourceManager.GetString("InstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шутка.
        /// </summary>
        public static string Joke {
            get {
                return ResourceManager.GetString("Joke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание шутки.
        /// </summary>
        public static string JokeCreator {
            get {
                return ResourceManager.GetString("JokeCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакторование шутки.
        /// </summary>
        public static string JokeEditor {
            get {
                return ResourceManager.GetString("JokeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to необходимо.
        /// </summary>
        public static string JokeRequiresName {
            get {
                return ResourceManager.GetString("JokeRequiresName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига : .
        /// </summary>
        public static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того чтобы посмотреть все шутки, которые вы использовали в сценариях той, или иной лиги, выберите имя интересующей лиги. Для того, чтобы посмотреть все шутки, не использованные вами ни в одной лиге – поставьте галочку &quot;Не паленные&quot;.
        /// </summary>
        public static string LeagueFilterToolTip {
            get {
                return ResourceManager.GetString("LeagueFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название : .
        /// </summary>
        public static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы создать новый сценарий.
        /// </summary>
        public static string NewScriptToolTip {
            get {
                return ResourceManager.GetString("NewScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая версия: .
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не паленные.
        /// </summary>
        public static string NotShot {
            get {
                return ResourceManager.GetString("NotShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указана.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только названия шуток (рыба).
        /// </summary>
        public static string OnlyJokeNames {
            get {
                return ResourceManager.GetString("OnlyJokeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделитесь вашим мнением о программе:.
        /// </summary>
        public static string OurGroup {
            get {
                return ResourceManager.GetString("OurGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петуда.
        /// </summary>
        public static string Petuda {
            get {
                return ResourceManager.GetString("Petuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа позволяет :.
        /// </summary>
        public static string ProgrammAllows {
            get {
                return ResourceManager.GetString("ProgrammAllows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитить данные из файла:.
        /// </summary>
        public static string ReadFileErrorText {
            get {
                return ResourceManager.GetString("ReadFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения данных.
        /// </summary>
        public static string ReadFileErrorTitle {
            get {
                return ResourceManager.GetString("ReadFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы удалить выбранную шутку из текущего сценария.
        /// </summary>
        public static string RemoveJokeFromScriptToolTip {
            get {
                return ResourceManager.GetString("RemoveJokeFromScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно должно быть заполнено.
        /// </summary>
        public static string RequiredToolTip {
            get {
                return ResourceManager.GetString("RequiredToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите,чтобы сохранить шутку. Если у шутки нет названия, то её сохранить нельзя..
        /// </summary>
        public static string SaveJokeToolTip {
            get {
                return ResourceManager.GetString("SaveJokeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите,чтобы сохранить сценарий. Если у сценария нет названия, то его сохранить нельзя..
        /// </summary>
        public static string SaveScriptToolTip {
            get {
                return ResourceManager.GetString("SaveScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценарий.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание сценария.
        /// </summary>
        public static string ScriptCreator {
            get {
                return ResourceManager.GetString("ScriptCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение сценария.
        /// </summary>
        public static string ScriptEditor {
            get {
                return ResourceManager.GetString("ScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для генерации документа сценария необходимо выбрать сам сценарий..
        /// </summary>
        public static string ScriptNotSelectedDocGenText {
            get {
                return ResourceManager.GetString("ScriptNotSelectedDocGenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран сценарий.
        /// </summary>
        public static string ScriptNotSelectedTitle {
            get {
                return ResourceManager.GetString("ScriptNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценарии.
        /// </summary>
        public static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кликните, чтобы открыть или закрыть панель сценария.
        /// </summary>
        public static string ScriptsToolTip {
            get {
                return ResourceManager.GetString("ScriptsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этап (что):.
        /// </summary>
        public static string ScriptWhat {
            get {
                return ResourceManager.GetString("ScriptWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига (где):.
        /// </summary>
        public static string ScriptWhere {
            get {
                return ResourceManager.GetString("ScriptWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор даты.
        /// </summary>
        public static string SelectADate {
            get {
                return ResourceManager.GetString("SelectADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать существующий сценарий.
        /// </summary>
        public static string SelectExistingScript {
            get {
                return ResourceManager.GetString("SelectExistingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поехали!.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тэги : .
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тегами могут быть любые слова, котороые помогут вам найти эту шутку. Тэги разделяются между собой либо пробелом, либо запятой..
        /// </summary>
        public static string TagsToolTip {
            get {
                return ResourceManager.GetString("TagsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст : .
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск шуток по их тексту, названию и тэгам. Чтобы искать – введите текст..
        /// </summary>
        public static string TextFilterToolTip {
            get {
                return ResourceManager.GetString("TextFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При выборе темы показываются все шутки из базы на эту тему.
        /// </summary>
        public static string ThemeFilterToolTip {
            get {
                return ResourceManager.GetString("ThemeFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема : .
        /// </summary>
        public static string ThemeTitle {
            get {
                return ResourceManager.GetString("ThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Дата игры уже прошла..
        /// </summary>
        public static string UnableToEditScript {
            get {
                return ResourceManager.GetString("UnableToEditScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальней об изменениях:.
        /// </summary>
        public static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая версия Петуды доступна для скачивания.
        /// </summary>
        public static string UpdateVersionIsAvaliable {
            get {
                return ResourceManager.GetString("UpdateVersionIsAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С названиями шуток.
        /// </summary>
        public static string WithJokeNames {
            get {
                return ResourceManager.GetString("WithJokeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без названий шуток.
        /// </summary>
        public static string WithOutJokeNames {
            get {
                return ResourceManager.GetString("WithOutJokeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось записать данные в файл:.
        /// </summary>
        public static string WriteFileErrorText {
            get {
                return ResourceManager.GetString("WriteFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи данных.
        /// </summary>
        public static string WriteFileErrorTitle {
            get {
                return ResourceManager.GetString("WriteFileErrorTitle", resourceCulture);
            }
        }
    }
}
