//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petuda.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petuda.ViewModels.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать!
        ///База готова к добавлению шуток. Чтобы записать в базу новую шутку, нажмите на кнопку «Создать». Либо дважды кликните где-нибудь здесь..
        /// </summary>
        internal static string BaseIsEmpty {
            get {
                return ResourceManager.GetString("BaseIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается сохранить файл «..\Petuda\Data\{0}» на диск. Возможно, папка, в которой находиться файл, защищена от записи..
        /// </summary>
        internal static string CantWriteFileErrorMessage {
            get {
                return ResourceManager.GetString("CantWriteFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петуде не удалось наладить взаимодействие с вашим MS Word. Эта ошибка может возникать и в случае, если у вас не установелен Word..
        /// </summary>
        internal static string DocumentGenerationErrorText {
            get {
                return ResourceManager.GetString("DocumentGenerationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка генерации документа.
        /// </summary>
        internal static string DocumentGenerationErrorTitle {
            get {
                return ResourceManager.GetString("DocumentGenerationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден:
        ///{0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата игры:.
        /// </summary>
        internal static string GameDate {
            get {
                return ResourceManager.GetString("GameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная шутка была замечена хотя бы в одном из уже сыгранных вами сценариев. После того как дата игры сценария прошла – изменения этого сценраия невозможны..
        /// </summary>
        internal static string JokeCantBeDeletedText {
            get {
                return ResourceManager.GetString("JokeCantBeDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шутка не может быть удалена из базы.
        /// </summary>
        internal static string JokeCantBeDeletedTitle {
            get {
                return ResourceManager.GetString("JokeCantBeDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено шуток, удовлетворяющих условиям поиска.
        ///Попробуйте изменить параметры поиска..
        /// </summary>
        internal static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указана.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить шутку: {0} ? Если эта шутка использовалась в ещё не сыгранных сценариях, она будет из них удалена..
        /// </summary>
        internal static string RemoveJokeText {
            get {
                return ResourceManager.GetString("RemoveJokeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление шутки.
        /// </summary>
        internal static string RemoveJokeTitle {
            get {
                return ResourceManager.GetString("RemoveJokeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить сценарий:.
        /// </summary>
        internal static string RemoveScriptText {
            get {
                return ResourceManager.GetString("RemoveScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление сценария.
        /// </summary>
        internal static string RemoveScriptTitle {
            get {
                return ResourceManager.GetString("RemoveScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шутка, которую вы хотите добавить в сценарий уже находится в нём под номером {0}. Если это рефрен, то шутка врдяд ли должна быть полностью идентичной..
        /// </summary>
        internal static string ScriptContainsJokeText {
            get {
                return ResourceManager.GetString("ScriptContainsJokeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная шутка уже в сенарии.
        /// </summary>
        internal static string ScriptContainsJokeTitle {
            get {
                return ResourceManager.GetString("ScriptContainsJokeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленная дата игры выбранного сценария прошла, значит, игра уже состоялась. Изменять, или удалять сыгранные сценарии нельзя – они уже история..
        /// </summary>
        internal static string ScriptIsPlayedMessageText {
            get {
                return ResourceManager.GetString("ScriptIsPlayedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный сценарий уже сыгран.
        /// </summary>
        internal static string ScriptIsPlayedTitle {
            get {
                return ResourceManager.GetString("ScriptIsPlayedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получилось добавить шутку в сценарий, так как сценарий не выбран. Чтобы добавить шутку в сценарий – откройте панель сценариев справа, и выберете в ней нужный сценарий. Затем попробуйте ещё раз..
        /// </summary>
        internal static string ScriptNotSelectedMessageText {
            get {
                return ResourceManager.GetString("ScriptNotSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран сценарий.
        /// </summary>
        internal static string ScriptNotSelectedTitle {
            get {
                return ResourceManager.GetString("ScriptNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбирая эту дату игры вы перенесёте редактируемый вами сценарий в историю.  Этот сценарий нельзя будет удалить, или изменить. Вы подтверждаете ваш выбор даты?.
        /// </summary>
        internal static string SelectedGameDateHasExpiredText {
            get {
                return ResourceManager.GetString("SelectedGameDateHasExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранная дата игры уже прошла.
        /// </summary>
        internal static string SelectedGameDateHasExpiredTitle {
            get {
                return ResourceManager.GetString("SelectedGameDateHasExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Петуда обнаружила обновление. Хотите его установить?.
        /// </summary>
        internal static string UpdateNotificationMessage {
            get {
                return ResourceManager.GetString("UpdateNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вышло обновление {0}.
        /// </summary>
        internal static string UpdateNotificationTitle {
            get {
                return ResourceManager.GetString("UpdateNotificationTitle", resourceCulture);
            }
        }
    }
}
